feat: update Brand, General, Services, and UI kit icons
planningcenter/icons pull request #61
Opened 2021-03-05 20:10 UTC by souporserious

This updates the Brand, General, Services, and UI Kit icon SVGs to match the latest Figma file. The changes in the General set are cleanup from some artboards being at 17x17 as well as adding missing icon variations. Brand is getting the Praise Charts logo used in Services to consolidate the set. Eventually any duplicates can be removed from the Services set as they can be replaced in code. Almost all of the UI Kit icons moved under Services as to reduce UI Kit to the bare minimum.

2021-03-05 21:04 UTC, tage commented on svg/general/outlined-clock.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M7.992 0C3.576 0 0 3.584 0 8C0 12.416 3.576 16 7.992 16C12.416 16 16 12.416 16 8C16 3.584 12.416 0 7.992 0ZM8 14.4C4.464 14.4 1.6 11.536 1.6 8C1.6 4.4
@souporserious are the fill and clip rules needed? Or do they get stripped out in the build process so that it doesn't matter?

2021-03-05 21:04 UTC, tage commented on svg/services/amazon.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M14.7272 12.427C15.2033 12.4709 15.3241 12.6137 15.2023 13.0718C15.0745 13.5519 14.8959 14.02 14.7472 14.4941C14.7262 14.563 14.7442 14.6428 14.7442 1
@souporserious Should the fill be black?

2021-03-05 21:04 UTC, tage commented on svg/services/envelope.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M15.2924 6.19488L8.86528 9.46497C8.52245 9.634 8.11391 9.71739 7.74151 9.71739C7.37459 9.71739 6.95728 9.63513 6.62322 9.47173L0.703176 6.52617C0.3778
@souporserious Same question as above about the fill value.

2021-03-05 21:33 UTC, souporserious commented
@tage thanks for catching those! All fixed up ✨

2021-03-06 02:08 UTC, chantastic requested changes
This looks good overall

For the `general` set, I've added a couple consistency considerations for the additions.

The deletions in `ui-kit` set will trigger a major bump and detailed changelog for folks updating.

I tried exporting using the documented procedure, and the new `Services` set polutes the global directory. It looks like the icons are not namespaces like the other icons.

<img width="194" alt="image" src="https://user-images.githubusercontent.com/658360/110191532-c0c03b00-7ddd-11eb-81c3-b01dcdf9ac5e.png">

Once the new services icons are namespaces, that should clear up.

2021-03-08 16:44 UTC, souporserious commented
Should have mentioned this, but the general changes are from icon tweaks to that actual SVGs I did not rename them to avoid any breaking changes. No one is relying on the ui-kit icon set from what I could grep so I think it's ok to make a breaking change there.

2021-03-08 16:46 UTC, souporserious commented on svg/services/amazon.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Ah yes it is, this is until Hugh has a chance to move over to the brand set allowing Services to delete it from the set.

2021-03-08 16:54 UTC, tage commented
@souporserious has the namespace issue been rectified? @chantastic Once the namespace pollution is cleared up are we good to proceed with a version bump?

2021-03-08 17:01 UTC, chantastic commented
@tage

- [ ] the two of the `general` icon additions still require name changes
- [x] looks like icons are now namespaced

if services paths cannot be merged, then this is blocked on #61

2021-03-08 20:09 UTC, souporserious commented
`remove` has been renamed to `minus`. Changing `search` to `magnifying-glass` will be a breaking change for everyone so probably worth doing that in a future PR.

2021-03-08 22:17 UTC, chantastic commented
resolved by #62 and #60

2021-03-08 22:17 UTC, closed without merging